# Generated by Django 5.0.6 on 2026-07-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialties', to='therapists.department')),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='therapists/photos/')),
                ('short_bio', models.CharField(help_text='نمایش\u200cداده\u200cشده در بلوک\u200cهای پیش\u200cنمایش', max_length=300)),
                ('full_bio', models.TextField(help_text='نمایش\u200cداده\u200cشده در صفحه پروفایل کامل')),
                ('age', models.PositiveSmallIntegerField()),
                ('years_active', models.PositiveSmallIntegerField(default=0)),
                ('is_head_of_institute', models.BooleanField(default=False, help_text='فقط برای دکتر سارا اکبرزاده فعال است — جلسه اول همه مراجعین جدید با ایشان برگزار می\u200cشود.')),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('departments', models.ManyToManyField(blank=True, related_name='therapists', to='therapists.department')),
                ('specialties', models.ManyToManyField(blank=True, related_name='therapists', to='therapists.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_head_of_institute', '-years_active'],
            },
        ),
    ]
