# Generated by Django 5.0.6 on 2026-07-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('therapists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_before_session', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salary_safe', models.BooleanField(default=True, help_text='محاسبه\u200cشده بر اساس قانون ۴ روز — تصمیم نهایی نیست')),
                ('decided_by_head', models.BooleanField(default=False, help_text='آیا دکتر اکبرزاده تصمیم نهایی را ثبت کرده؟')),
                ('final_salary_deduction_applied', models.BooleanField(default=False)),
                ('deduction_amount_rials', models.PositiveBigIntegerField(default=0)),
                ('head_notes', models.TextField(blank=True, help_text='یادداشت دکتر اکبرزاده درباره این تصمیم')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_record', to='scheduling.booking')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayrollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_salary_rials', models.PositiveBigIntegerField(default=0)),
                ('total_deductions_rials', models.PositiveBigIntegerField(default=0)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_summaries', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('therapist', 'year', 'month')},
            },
        ),
    ]
