# Generated by Django 5.0.6 on 2026-07-03 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_rials', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refund_requested', 'در انتظار بازگشت وجه'), ('refunded', 'بازگشت داده\u200cشده')], default='pending', max_length=20)),
                ('gateway', models.CharField(default='zarinpal', max_length=30)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('card_pan_masked', models.CharField(blank=True, help_text='فقط نسخه ماسک\u200cشده — از پاسخ درگاه', max_length=25)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scheduling.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('saved_card_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.savedcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('client_cancelled_in_time', 'لغو به\u200cموقع توسط مراجع'), ('therapist_cancelled', 'لغو توسط درمانگر')], max_length=40)),
                ('amount_rials', models.PositiveBigIntegerField()),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
