# Generated by Django 5.0.6 on 2026-07-03 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to='therapists.therapistprofile')),
            ],
            options={
                'unique_together': {('client', 'therapist', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('free', 'آزاد'), ('pending_payment', 'در انتظار پرداخت'), ('booked', 'رزرو و پرداخت\u200cشده')], default='free', max_length=20)),
                ('is_recurring_hold', models.BooleanField(default=False)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_slots', to=settings.AUTH_USER_MODEL)),
                ('recurring_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='scheduling.recurringbooking')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting_payment', 'در انتظار پرداخت'), ('confirmed', 'تأیید شده'), ('cancelled_by_client', 'لغو توسط مراجع'), ('cancelled_by_therapist', 'لغو توسط درمانگر'), ('completed', 'برگزار شده')], default='awaiting_payment', max_length=30)),
                ('is_weekly_recurring', models.BooleanField(default=False)),
                ('is_first_session', models.BooleanField(default=False, help_text='جلسه ارزیابی اولیه با دکتر اکبرزاده')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='therapists.therapistprofile')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='scheduling.sessionslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='therapists.therapistprofile')),
            ],
            options={
                'verbose_name_plural': 'Weekly availabilities',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='NotifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='therapists.therapistprofile')),
            ],
            options={
                'unique_together': {('client', 'therapist', 'weekday', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='sessionslot',
            index=models.Index(fields=['therapist', 'date'], name='scheduling__therapi_49f222_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionslot',
            unique_together={('therapist', 'date', 'start_time')},
        ),
    ]
